const mockProjects = [
  {
    name: "Project Name",
    id: "P-001",
    progress: { total: 14, completed: "07" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [
      { name: "John Doe" },
      { name: "Jane Smith" },
      { name: "Mike Brown" },
      { name: "Mike Brown" },
    ],
    files: 12,
    stage: "Not Started",
  },
  {
    name: "Project Alpha",
    id: "P-002",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Not Started",
  },
  {
    name: "Project Alpha",
    id: "P-003",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Not Started",
  },
  {
    name: "Project Alpha",
    id: "P-004",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Not Started",
  },
  {
    name: "Project Alpha",
    id: "P-005",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Not Started",
  },
  {
    name: "Project Alpha",
    id: "P-006",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "In Progress",
  },
  {
    name: "Project Alpha",
    id: "P-007",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "In Progress",
  },
  {
    name: "Project Alpha",
    id: "P-008",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "In Progress",
  },
  {
    name: "Project Alpha",
    id: "P-009",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "In Progress",
  },
  {
    name: "Project Alpha",
    id: "P-010",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "In Progress",
  },
  {
    name: "Project Alpha",
    id: "P-011",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Archived",
  },
  {
    name: "Project Alpha",
    id: "P-012",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Archived",
  },
  {
    name: "Project Alpha",
    id: "P-013",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Archived",
  },
  {
    name: "Project Alpha",
    id: "P-014",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Archived",
  },
  {
    name: "Project Alpha",
    id: "P-015",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Completed",
  },
  {
    name: "Project Alpha",
    id: "P-016",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Completed",
  },
  {
    name: "Project Alpha",
    id: "P-017",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Completed",
  },
  {
    name: "Project Alpha",
    id: "P-018",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Completed",
  },
  {
    name: "Project Alpha",
    id: "P-019",
    progress: { total: 14, completed: "10" },
    date: { start: "01/01/2024", end: "31/01/2024" },
    owner: "Techyon",
    associated_team: "",
    team: [{ name: "John Doe" }, { name: "Jane Smith" }],
    files: 8,
    stage: "Completed",
  },
];

export default mockProjects;
