const mockTask = [
    {
      name: "Project Name",
      id: "P-11",
      progress: {
        total: 14,
        completed: "07",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [
        { name: "John Doe" },
        { name: "Jane Smith" },
        { name: "Mike Brown" },
        { name: "Mike Brown" },
      ],
      files: 12,
      status: "delayed",
      stage: "In Review",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Review",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Review",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Review",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Review",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Progress",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Progress",
    },
  
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Progress",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Progress",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Progress",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Revision",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Revision",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Revision",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "In Revision",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "Completed",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "Completed",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "Completed",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "Completed",
    },
    {
      name: "Project Alpha",
      id: "P-12",
      progress: {
        total: 14,
        completed: "10",
      },
      date: {
        start: "01/01/2024",
        end: "31/01/2024",
      },
      owner:"Techyon",
      associated_team:'',
      team: [{ name: "John Doe" }, { name: "Jane Smith" }],
      files: 8,
      status: "on-track",
      stage: "Completed",
    },
  
  
  ];
  
  export default mockTask;
  